#!/usr/bin/env python3
"""
AI Code Review Script
This script uses OpenAI API to review Dart code changes
"""

import os
import sys
import subprocess
import json
from datetime import datetime

# Get the files to review
files = sys.argv[1:]

if not files:
    print("No files to review")
    sys.exit(0)

print("\n=== AI Code Review ===")
print(f"Reviewing {len(files)} files...")

# Create review results directory
review_dir = ".trae/reviews"
os.makedirs(review_dir, exist_ok=True)

# Review each file
for file_path in files:
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        continue

    print(f"\nReviewing: {file_path}")

    # Read the file content
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Get git diff for the file
    try:
        diff = subprocess.check_output(
            ['git', 'diff', 'HEAD', file_path],
            stderr=subprocess.STDOUT,
            text=True
        )
    except subprocess.CalledProcessError as e:
        diff = e.output

    # Generate review prompt
    prompt = f"""
You are a senior Flutter/Dart developer and code reviewer. Review the following Dart file:

File: {file_path}

Content:
{content}

Git diff:
{diff}

Please provide a comprehensive review covering:
1. Code quality and best practices
2. Potential bugs or issues
3. Performance optimizations
4. Security concerns
5. Readability and maintainability
6. Compliance with Flutter/Dart guidelines

Format your response as JSON with the following structure:
{
  "file": "<file_path>",
  "timestamp": "<iso_timestamp>",
  "issues": [
    {
      "severity": "<critical|high|medium|low>",
      "title": "<issue_title>",
      "description": "<issue_description>",
      "suggestion": "<fix_suggestion>"
    }
  ],
  "summary": "<overall_summary>"
}
"""

    # For now, we'll just create a placeholder review
    # In a real implementation, this would call an AI API
    review = {
        "file": file_path,
        "timestamp": datetime.now().isoformat(),
        "issues": [
            {
                "severity": "medium",
                "title": "Placeholder issue",
                "description": "This is a placeholder for AI-generated review",
                "suggestion": "Implement actual AI review"
            }
        ],
        "summary": "Placeholder review - would be generated by AI in a real implementation"
    }

    # Save review to file
    review_file = os.path.join(review_dir, f"{os.path.basename(file_path)}.review.json")
    with open(review_file, 'w', encoding='utf-8') as f:
        json.dump(review, f, indent=2)

    print(f"Review saved to: {review_file}")

print("\n=== AI Code Review Complete ===")
